#!/usr/bin/env bash

# ref: http://qiita.com/b4b4r07/items/24872cdcbec964ce2178#deploy

set -eu

repo="github.com/izumin5210/dotfiles"
dotpath="${HOME}/src/${repo}"
github_url="https://${repo}"

has() {
  return `type $1 > /dev/null 2>&1`
}

if has "git"; then
  git clone --recursive "${github_url}" "${dotpath}"
elif has "curl" || has "wget"; then
  tarball="${github_url}/archive/master.tar.gz"

  if has "curl"; then
    curl -L "${tarball}"
  elif has "wget"; then
    wget -O - "${tarball}"
  fi | tar xv -

  mv -f dotfiles-master "${dotpath}"
else
  exit 1
fi

cd "${dotpath}"
if [ $? -ne 0 ]; then
  exit 1
fi

bin/setup_mitamae
bin/mitamae local lib/recipe.rb
