#!/usr/bin/env bash

# ref: http://qiita.com/b4b4r07/items/24872cdcbec964ce2178#deploy

set -eu

has() {
  return `type $1 > /dev/null 2>&1`
}

REPO="github.com/izumin5210/dotfiles"
DOTPATH="${HOME}/src/${REPO}"

download() {
  local github_url="https://${REPO}"

  if has "git"; then
    git clone --recursive "${github_url}" "${DOTPATH}"
  elif has "curl" || has "wget"; then
    tarball="${github_url}/archive/main.tar.gz"

    if has "curl"; then
      curl -L "${tarball}"
    elif has "wget"; then
      wget -O - "${tarball}"
    fi | tar xv -

    mv -f dotfiles-main "${dotpath}"
  else
    exit 1
  fi
}

if [ ! -d $DOTPATH ]; then
  download
fi

cd $DOTPATH

if [ $? -ne 0 ]; then
  exit 1
fi

if [ "${CODESPACES:-"false"}" = "true" ]; then
  ./bin/setup-codespace
else
  echo "TODO: not yet implemented"
  exit 1
fi
