#!/usr/bin/env bash

brew update
brew upgrade

brew tap sanemat/font
brew tap caskroom/cask
brew tap caskroom/fonts
brew tap caskroom/versions

# ==== xquartz ====
brew cask install xquartz

# ================================================================
# formulas
# ================================================================

brew install git
brew install zsh --disable-etc-dir
brew install zsh-completions
brew install vim --with-lua --with-python3
brew install macvim --with-lua --with-python3
brew install neovim
brew install tmux

brew install android-sdk
brew install android-ndk
brew install lua
brew install go

brew install hub
brew install heroku-toolbelt
brew install imagemagick
brew install pngquant
brew install gnuplot --with-x --latex
brew install gcc
brew install jq
brew install curl
brew install highlight
brew install tree
brew install tig
brew install git-flow
brew install peco
brew install ghq
brew install git-secrets
brew install direnv
brew install gsed
brew install ripgrep
brew install gibo

# https://github.com/atom/atom/issues/3093
brew install reattach-to-user-namespace

brew install chromedriver
brew install terminal-notifier

# ==== sanemat/font ====
# > Error: /usr/local/opt/automake not present or broken
# > Please reinstall automake. Sorry :(
brew install automake

brew install ricty --vim-powerline

# ==== after brew brew install ====
brew linkapps
brew cleanup

# ================================================================
# casks
# ================================================================

brew cask update

brew cask install alfred && brew cask alfred link

brew cask install android-studio
brew cask install iterm2
brew cask install arduino
brew cask install docker-toolbox
brew cask install visual-studio-code
brew install caskroom/versions/docker-edge

brew cask install google-chrome
brew cask install google-japanese-ime
brew cask install google-drive
brew cask install firefox
brew cask install skitch
brew cask install dropbox
brew cask install skype
brew cask install dash
brew cask install adobe-creative-cloud
brew cask install 1password

brew cask install caffeine
brew cask install appcleaner
brew cask install day-o
brew cask install bettertouchtool
brew cask install monolingual
brew cask install the-unarchiver
brew cask install android-file-transfer
brew cask install pandoc
brew cask install licecap
brew cask install jasper
brew cask install insomnia
brew cask install postico

# ================================================================
# fonts
# ================================================================

brew cask install font-inconsolata
brew cask install font-fontawesome
brew cask install font-m-plus
brew cask install font-rounded-m-plus
brew cask install font-noto-sans-cjk-jp
brew cask install font-raleway
brew cask install font-raleway-dots

brew cask cleanup

# ================================================================
# whalebrew
# ================================================================

whalebrew install whalebrew/awscli
