#!/usr/bin/env bash

echo 'Installing golang packages...'
go get -u github.com/nsf/gocode
go get -u github.com/golang/lint/golint
go get -u github.com/motemen/gore
go get -u github.com/k0kubun/pp
go get -u golang.org/x/tools/cmd/godoc
