region              = "ap-northeast-1"
name                = "izumin5210-dotfiles"
domain              = "izum.in"
subdomain           = "dot"
install_script_path = "../install"
install_script_name = "install"
