include_cookbook 'functions'

include_cookbook 'homebrew'
# include_cookbook 'zsh'
# include_cookbook 'git'
# include_cookbook 'tmux'
# include_cookbook 'vim'
include_cookbook 'rbenv'
include_cookbook 'nodenv'
include_cookbook 'yarn'
# include_cookbook 'golang'
include_cookbook 'android'
# include_cookbook 'fzf'
# include_cookbook 'ghq'
# include_cookbook 'ripgrep'
# include_cookbook 'alacritty'
include_cookbook 'docker'
include_cookbook 'whalebrew'
# include_cookbook 'karabiner'
# include_cookbook 'bin'
include_cookbook 'macos_apps'
include_cookbook 'tools'
include_cookbook 'macos_defaults'
# include_cookbook 'fonts'
