#!/usr/bin/env bash

# WIP commit detection
#
# ref: http://qiita.com/takose/items/beed51b56aeec396e30e

isLastCommitWIP() {
  return `git log -1 --oneline --pretty=format:'%s' | grep -q -e '^\[WIP\]'`
}

doesCurrentCommitAmmend() {
  last_commit=`git log -1 --date=raw --pretty=format:"%ad"`
  current_commit=$GIT_AUTHOR_DATE
  return `echo "$current_commit" | grep -q -v "$last_commit"`
}

if isLastCommitWIP && doesCurrentCommitAmmend; then
  echo "last commit is wip commit!!"
  exit 1
fi
