include_cookbook 'functions'

# include_cookbook 'rbenv'
# include_cookbook 'pyenv'
# include_cookbook 'nodenv'
# include_cookbook 'yarn'
# include_cookbook 'golang'
# include_cookbook 'android'
# include_cookbook 'hammerspoon'
# include_cookbook 'alacritty'
# include_cookbook 'docker'
# include_cookbook 'whalebrew'
# include_cookbook 'tools'
# include_cookbook 'fonts'
# include_cookbook 'macos_apps'
# include_cookbook 'macos_defaults'
