services:
  postgres:
    image: postgres:18@sha256:311136771dca6826c3b6e691ebf8cb6e896e165074bc57a728f9619f25f0c4c7
    container_name: the-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - the-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mysql:
    image: mysql:8@sha256:d36d39a64cd12a5c1cc9e6aa2bfb5f8d4c81a2f6586e0a04a9ae13939db02209
    container_name: the-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - the-mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:8@sha256:2838d5524559494f6f1cd66e97e76b200d64a633a8614200620755ed395daf32
    container_name: the-redis
    volumes:
      - the-redis:/data
    ports:
      - 6379:6379

volumes:
  the-postgres:
    name: the-postgres
  the-mysql:
    name: the-mysql
  the-redis:
    name: the-redis
