services:
  postgres:
    image: postgres:18@sha256:22c89fe0d0f507606260237fd55e51f6137f58b2d5bcf6152242b96d9fe8f9a4
    container_name: the-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - the-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mysql:
    image: mysql:8@sha256:c831a0f11348d402b43d77453e17d770be2eef356615a2823fe0f5a0d6c8b9af
    container_name: the-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - the-mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:8@sha256:2838d5524559494f6f1cd66e97e76b200d64a633a8614200620755ed395daf32
    container_name: the-redis
    volumes:
      - the-redis:/data
    ports:
      - 6379:6379

volumes:
  the-postgres:
    name: the-postgres
  the-mysql:
    name: the-mysql
  the-redis:
    name: the-redis
