services:
  postgres:
    image: postgres:18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
    container_name: the-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - the-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mysql:
    image: mysql:8@sha256:b3b90af2a6552ae30c266fdb7d5dd55f3afb72404bb78d37fe8a23eb857fd3fb
    container_name: the-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - the-mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis:8@sha256:077ba791400f390cb96d9d419d90259d5e72e697fca7abc3bbde6d83285d7346
    container_name: the-redis
    volumes:
      - the-redis:/data
    ports:
      - 6379:6379

volumes:
  the-postgres:
    name: the-postgres
  the-mysql:
    name: the-mysql
  the-redis:
    name: the-redis
