#!/usr/bin/env bash
#
# Create git repository

set -euo pipefail

version="0.2.0"

usage() {
  local github_user=${1}
  local github_sandbox=${2}
  cat <<EOF
$(basename ${0}) - Create a remote repository

Usage:
    $(basename ${0}) [-s] <name>

Options:
    --sandbox, -s     create repository under github.com/${github_user}-sandbox
    --sandbox-name <name>
                      set sandbox user/organization name (default: ${github_sandbox})
    --private, -p     create private repository
    --version, -v     print $(basename ${0}) version
    --help, -h        print this
EOF
}

version() {
  echo "$(basename ${0}) version ${version}"
}

create() {
  local name=${1}
  local github_user=${2}
  local is_sandbox=${3}
  local github_sandbox=${4}

  local repo

  if [ $is_sandbox -eq 1 ]; then
    repo="${github_sandbox}/${name}"
  else
    repo="${github_user}/${name}"
  fi

  local path="$(pwd)/${name}"

  if type ghq >/dev/null 2>&1; then
    src_dir=$(ghq root)
    if [ -n "${src_dir}" ]; then
      path="${src_dir}/github.com/${repo}"
    fi
  fi

  printutil section "Create ${repo}"
  printutil subsection "mkdir"
  mkdir -p $path
  cd $path

  printutil subsection "Initialize repository"
  git init
  git commit --allow-empty -m "Initial commit"

  if [ $is_private -eq 1 ]; then
    printutil subsection "Create private repository in github"
    hub create -p $repo
  else
    printutil subsection "Create repository in github"
    hub create $repo
  fi
}

if [ $# -lt 1 ]; then
  printutil error "You should pass a repository name."
  printutil error "Try '-h' option for more information."
  exit 1
fi

github_user=$(git config github.user)

if [ -z "${github_user}" ]; then
  printutil error "You should set 'git config github.user'."
  exit 1
fi

is_sandbox=0
is_private=0
github_sandbox="${github_user}-sandbox"

while [ $# -gt 0 ]; do
  case ${1} in
  --debug | -d)
    set -x
    ;;

  --sandbox | -s)
    is_sandbox=1
    ;;

  --sandbox-name)
    github_sandbox=${2}
    shift
    ;;

  --private | -p)
    is_private=1
    ;;

  --version | -v)
    version
    exit 0
    ;;

  --help | -h)
    usage $github_user $github_sandbox
    exit 0
    ;;

  *)
    create $1 $github_user $is_sandbox $github_sandbox
    exit 0
    ;;
  esac
  shift
done
