#!/usr/bin/env bash

set -euo pipefail

branch=$(git rev-parse --abbrev-ref @)

if [ $branch = "$(git default-branch)" ]; then
  echo "Current branch is NOT a feature branch."
  exit 1
else
  git add --all

  if git log -1 --pretty='%s' | grep -q -e "^\[WIP\]"; then
    git commit --amend --verbose --allow-empty
  else
    git commit --edit --verbose --allow-empty --message "[WIP] "
  fi
fi
