#!/usr/bin/env bash
#
#

set -eu

remoteName="${1:-origin}"
defaultBranch="$(git default-branch)"

printutil section "Start sync..."

printutil subsection "Checkout $defaultBranch"
git checkout $defaultBranch

printutil subsection "Pull $defaultBranch from $remoteName"
git pull $remoteName $defaultBranch

printutil subsection "Remove references that no longer exist on the remote"
git fetch --prune $remoteName

printutil subsection "Cleanup merged branches in local"
git clean-branch local

printutil subsection "Cleanup merged branches in remote"
git clean-branch remote
