package 'curl'
package 'direnv'
package 'envchain'
package 'gcc'
package 'ghq'
package 'gibo'
package 'gnu-sed'
package 'heroku'
package 'highlight'
package 'jq'
package 'kops'
package 'kubernetes-cli'
package 'lua'
package 'lv'
package 'ripgrep'
package 'terraform'
package 'tig'
package 'tree'

brew_tap 'creasty/tools'
package 'creasty/tools/rid'

brew_tap 'dtan4/tools'
package 'valec'
