package 'colordiff'
package 'coreutils'
package 'ctop'
package 'curl'
package 'direnv'
package 'envchain'
package 'gcc'
package 'ghq'
package 'gibo'
package 'git-secrets'
package 'gnu-sed'
package 'htop'
package 'jq'
package 'lua'
package 'lv'
package 'protobuf'
package 'prototool'
package 'ripgrep'
package 'terraform'
package 'tig'
package 'tree'
package 'watchman'
package 'wget'

brew_tap 'creasty/tools'
package 'creasty/tools/rid'

brew_tap 'dtan4/tools'
package 'valec'

brew_tap 'izumin5210/tools'
package 'grapi'

# kube
package 'kops'
package 'kubernetes-cli'
package 'stern'
brew_tap 'datawire/blackbird' # for telepresence
package 'telepresence'
