# https://aquaproj.github.io/docs/products/update-checksum-workflow/

name: update-aqua-checksum
on:
  workflow_call:

jobs:
  check-aqua-updates:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check aqua updates
        id: dirs
        run: |
          git diff --name-only "${{ github.event.pull_request.base.ref }}" \
            | grep -E '/(aqua\.yaml|/aqua-checksums\.json)$' \
            | xargs dirname \
            | sort -u \
            | jq -R -s -c 'split("\n") | map(select(length > 0))' \
            > update-dirs.json
          echo "json=$(cat update-dirs.json)"
          echo "json=$(cat update-dirs.json)" >> $GITHUB_OUTPUT

  update-aqua-checksums:
    needs: [check-aqua-updates]
    strategy:
      matrix:
        dir: ${{ fromJson(needs.check-aqua-updates.outputs.dirs.json) }}
    name: "Update aqua-checksums (${{ matrix.dir }})"
    uses: aquaproj/update-checksum-workflow/.github/workflows/update-checksum.yaml@8bce60cc4475128360bc32f00707abb874ca4a91 # v1.0.3
    permissions:
      contents: read
    with:
      aqua_version: v2.43.0
      prune: true
      working_directory: ${{ matrix.dir }}
    secrets:
      gh_app_id: ${{secrets.UPDATE_AQUA_CHECKSUM_APP_ID}}
      gh_app_private_key: ${{secrets.UPDATE_AQUA_CHECKSUM_APP_PRIVATE_KEY}}
